#!/bin/bash

cd experiments

total=$(ls -1 . | wc -l)
current=0

for dir in $(ls)
do 
    cd $dir
    
    echo "Running experiment $dir..."
    
    ./start_experiment.sh
    
    cd ..

    current=$((current+1))
    echo "Finished experiment $current of $total." >> progress.txt
    
done
